// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: fetch.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Timeout       int32                  `protobuf:"varint,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_fetch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FetchRequest) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Html          string                 `protobuf:"bytes,2,opt,name=html,proto3" json:"html,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_fetch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FetchResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *FetchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BrowserAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Script        string                 `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserAction) Reset() {
	*x = BrowserAction{}
	mi := &file_fetch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserAction) ProtoMessage() {}

func (x *BrowserAction) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserAction.ProtoReflect.Descriptor instead.
func (*BrowserAction) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{2}
}

func (x *BrowserAction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BrowserAction) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *BrowserAction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BrowserAction) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *BrowserAction) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type BrowserJobRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Profile         string                 `protobuf:"bytes,4,opt,name=profile,proto3" json:"profile,omitempty"`
	Recipe          string                 `protobuf:"bytes,5,opt,name=recipe,proto3" json:"recipe,omitempty"`
	TimeoutMs       int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Actions         []*BrowserAction       `protobuf:"bytes,7,rep,name=actions,proto3" json:"actions,omitempty"`
	Outputs         []string               `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Headers         map[string]string      `protobuf:"bytes,9,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ClosePage       bool                   `protobuf:"varint,10,opt,name=close_page,json=closePage,proto3" json:"close_page,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BrowserJobRequest) Reset() {
	*x = BrowserJobRequest{}
	mi := &file_fetch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserJobRequest) ProtoMessage() {}

func (x *BrowserJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserJobRequest.ProtoReflect.Descriptor instead.
func (*BrowserJobRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{3}
}

func (x *BrowserJobRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *BrowserJobRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BrowserJobRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BrowserJobRequest) GetProfile() string {
	if x != nil {
		return x.Profile
	}
	return ""
}

func (x *BrowserJobRequest) GetRecipe() string {
	if x != nil {
		return x.Recipe
	}
	return ""
}

func (x *BrowserJobRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *BrowserJobRequest) GetActions() []*BrowserAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *BrowserJobRequest) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *BrowserJobRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *BrowserJobRequest) GetClosePage() bool {
	if x != nil {
		return x.ClosePage
	}
	return false
}

type BrowserCookie struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Domain        string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Path          string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserCookie) Reset() {
	*x = BrowserCookie{}
	mi := &file_fetch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserCookie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserCookie) ProtoMessage() {}

func (x *BrowserCookie) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserCookie.ProtoReflect.Descriptor instead.
func (*BrowserCookie) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{4}
}

func (x *BrowserCookie) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrowserCookie) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *BrowserCookie) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *BrowserCookie) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type BrowserActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserActionResult) Reset() {
	*x = BrowserActionResult{}
	mi := &file_fetch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserActionResult) ProtoMessage() {}

func (x *BrowserActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserActionResult.ProtoReflect.Descriptor instead.
func (*BrowserActionResult) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{5}
}

func (x *BrowserActionResult) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BrowserActionResult) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BrowserActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrowserActionResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BrowserActionResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type BrowserJobResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	Html            string                 `protobuf:"bytes,6,opt,name=html,proto3" json:"html,omitempty"`
	Text            string                 `protobuf:"bytes,7,opt,name=text,proto3" json:"text,omitempty"`
	Json            string                 `protobuf:"bytes,8,opt,name=json,proto3" json:"json,omitempty"`
	Screenshot      []byte                 `protobuf:"bytes,9,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	Cookies         []*BrowserCookie       `protobuf:"bytes,10,rep,name=cookies,proto3" json:"cookies,omitempty"`
	DurationMs      int64                  `protobuf:"varint,11,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	FinalUrl        string                 `protobuf:"bytes,12,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	StatusCode      int32                  `protobuf:"varint,13,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // 0 when the browser cannot report navigation status.
	ContentType     string                 `protobuf:"bytes,14,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ActionResults   []*BrowserActionResult `protobuf:"bytes,15,rep,name=action_results,json=actionResults,proto3" json:"action_results,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BrowserJobResponse) Reset() {
	*x = BrowserJobResponse{}
	mi := &file_fetch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserJobResponse) ProtoMessage() {}

func (x *BrowserJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserJobResponse.ProtoReflect.Descriptor instead.
func (*BrowserJobResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{6}
}

func (x *BrowserJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BrowserJobResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *BrowserJobResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BrowserJobResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BrowserJobResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BrowserJobResponse) GetHtml() string {
	if x != nil {
		return x.Html
	}
	return ""
}

func (x *BrowserJobResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *BrowserJobResponse) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

func (x *BrowserJobResponse) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

func (x *BrowserJobResponse) GetCookies() []*BrowserCookie {
	if x != nil {
		return x.Cookies
	}
	return nil
}

func (x *BrowserJobResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *BrowserJobResponse) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *BrowserJobResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *BrowserJobResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *BrowserJobResponse) GetActionResults() []*BrowserActionResult {
	if x != nil {
		return x.ActionResults
	}
	return nil
}

type BrowserHealthRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BrowserHealthRequest) Reset() {
	*x = BrowserHealthRequest{}
	mi := &file_fetch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserHealthRequest) ProtoMessage() {}

func (x *BrowserHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserHealthRequest.ProtoReflect.Descriptor instead.
func (*BrowserHealthRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{7}
}

func (x *BrowserHealthRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *BrowserHealthRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type BrowserHealthResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ready           bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Message         string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BrowserHealthResponse) Reset() {
	*x = BrowserHealthResponse{}
	mi := &file_fetch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserHealthResponse) ProtoMessage() {}

func (x *BrowserHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserHealthResponse.ProtoReflect.Descriptor instead.
func (*BrowserHealthResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{8}
}

func (x *BrowserHealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BrowserHealthResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *BrowserHealthResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BrowserHealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EditorSessionCreateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url             string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	TtlSeconds      int32                  `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ViewportWidth   int32                  `protobuf:"varint,6,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	ViewportHeight  int32                  `protobuf:"varint,7,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	// Transient authorization; never echoed or logged. Requires editor.auth.v1.
	AuthorizationJson string `protobuf:"bytes,8,opt,name=authorization_json,json=authorizationJson,proto3" json:"authorization_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditorSessionCreateRequest) Reset() {
	*x = EditorSessionCreateRequest{}
	mi := &file_fetch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorSessionCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSessionCreateRequest) ProtoMessage() {}

func (x *EditorSessionCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSessionCreateRequest.ProtoReflect.Descriptor instead.
func (*EditorSessionCreateRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{9}
}

func (x *EditorSessionCreateRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorSessionCreateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorSessionCreateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EditorSessionCreateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *EditorSessionCreateRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *EditorSessionCreateRequest) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *EditorSessionCreateRequest) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

func (x *EditorSessionCreateRequest) GetAuthorizationJson() string {
	if x != nil {
		return x.AuthorizationJson
	}
	return ""
}

type EditorSessionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TtlSeconds      int32                  `protobuf:"varint,4,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	PageStateId     string                 `protobuf:"bytes,5,opt,name=page_state_id,json=pageStateId,proto3" json:"page_state_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditorSessionRequest) Reset() {
	*x = EditorSessionRequest{}
	mi := &file_fetch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSessionRequest) ProtoMessage() {}

func (x *EditorSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSessionRequest.ProtoReflect.Descriptor instead.
func (*EditorSessionRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{10}
}

func (x *EditorSessionRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorSessionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EditorSessionRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *EditorSessionRequest) GetPageStateId() string {
	if x != nil {
		return x.PageStateId
	}
	return ""
}

type EditorSessionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error           string                 `protobuf:"bytes,7,opt,name=error,proto3" json:"error,omitempty"`
	ExpiresAtUnixMs int64                  `protobuf:"varint,8,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"`
	PageStateId     string                 `protobuf:"bytes,9,opt,name=page_state_id,json=pageStateId,proto3" json:"page_state_id,omitempty"`
	CurrentUrl      string                 `protobuf:"bytes,10,opt,name=current_url,json=currentUrl,proto3" json:"current_url,omitempty"`
	ViewportWidth   int32                  `protobuf:"varint,11,opt,name=viewport_width,json=viewportWidth,proto3" json:"viewport_width,omitempty"`
	ViewportHeight  int32                  `protobuf:"varint,12,opt,name=viewport_height,json=viewportHeight,proto3" json:"viewport_height,omitempty"`
	Screenshot      []byte                 `protobuf:"bytes,13,opt,name=screenshot,proto3" json:"screenshot,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditorSessionResponse) Reset() {
	*x = EditorSessionResponse{}
	mi := &file_fetch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorSessionResponse) ProtoMessage() {}

func (x *EditorSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorSessionResponse.ProtoReflect.Descriptor instead.
func (*EditorSessionResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{11}
}

func (x *EditorSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditorSessionResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorSessionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EditorSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditorSessionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EditorSessionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditorSessionResponse) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *EditorSessionResponse) GetPageStateId() string {
	if x != nil {
		return x.PageStateId
	}
	return ""
}

func (x *EditorSessionResponse) GetCurrentUrl() string {
	if x != nil {
		return x.CurrentUrl
	}
	return ""
}

func (x *EditorSessionResponse) GetViewportWidth() int32 {
	if x != nil {
		return x.ViewportWidth
	}
	return 0
}

func (x *EditorSessionResponse) GetViewportHeight() int32 {
	if x != nil {
		return x.ViewportHeight
	}
	return 0
}

func (x *EditorSessionResponse) GetScreenshot() []byte {
	if x != nil {
		return x.Screenshot
	}
	return nil
}

type EditorCommandRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion   string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId         string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId         string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CommandId         string                 `protobuf:"bytes,4,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	PageStateId       string                 `protobuf:"bytes,5,opt,name=page_state_id,json=pageStateId,proto3" json:"page_state_id,omitempty"`
	Type              string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	LocatorStrategy   string                 `protobuf:"bytes,7,opt,name=locator_strategy,json=locatorStrategy,proto3" json:"locator_strategy,omitempty"`
	LocatorExpression string                 `protobuf:"bytes,8,opt,name=locator_expression,json=locatorExpression,proto3" json:"locator_expression,omitempty"`
	Value             string                 `protobuf:"bytes,9,opt,name=value,proto3" json:"value,omitempty"`
	TimeoutMs         int32                  `protobuf:"varint,10,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Confirmed         bool                   `protobuf:"varint,11,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	HasPosition       bool                   `protobuf:"varint,12,opt,name=has_position,json=hasPosition,proto3" json:"has_position,omitempty"`
	X                 float64                `protobuf:"fixed64,13,opt,name=x,proto3" json:"x,omitempty"`
	Y                 float64                `protobuf:"fixed64,14,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditorCommandRequest) Reset() {
	*x = EditorCommandRequest{}
	mi := &file_fetch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorCommandRequest) ProtoMessage() {}

func (x *EditorCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorCommandRequest.ProtoReflect.Descriptor instead.
func (*EditorCommandRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{12}
}

func (x *EditorCommandRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorCommandRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorCommandRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EditorCommandRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *EditorCommandRequest) GetPageStateId() string {
	if x != nil {
		return x.PageStateId
	}
	return ""
}

func (x *EditorCommandRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EditorCommandRequest) GetLocatorStrategy() string {
	if x != nil {
		return x.LocatorStrategy
	}
	return ""
}

func (x *EditorCommandRequest) GetLocatorExpression() string {
	if x != nil {
		return x.LocatorExpression
	}
	return ""
}

func (x *EditorCommandRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EditorCommandRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *EditorCommandRequest) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *EditorCommandRequest) GetHasPosition() bool {
	if x != nil {
		return x.HasPosition
	}
	return false
}

func (x *EditorCommandRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *EditorCommandRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type EditorCommandResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProtocolVersion   string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	CommandId         string                 `protobuf:"bytes,3,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Status            string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode         string                 `protobuf:"bytes,5,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error             string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	BeforePageStateId string                 `protobuf:"bytes,7,opt,name=before_page_state_id,json=beforePageStateId,proto3" json:"before_page_state_id,omitempty"`
	AfterPageStateId  string                 `protobuf:"bytes,8,opt,name=after_page_state_id,json=afterPageStateId,proto3" json:"after_page_state_id,omitempty"`
	FinalUrl          string                 `protobuf:"bytes,9,opt,name=final_url,json=finalUrl,proto3" json:"final_url,omitempty"`
	DurationMs        int64                  `protobuf:"varint,10,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	LocatorStrategy   string                 `protobuf:"bytes,11,opt,name=locator_strategy,json=locatorStrategy,proto3" json:"locator_strategy,omitempty"`
	LocatorExpression string                 `protobuf:"bytes,12,opt,name=locator_expression,json=locatorExpression,proto3" json:"locator_expression,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EditorCommandResponse) Reset() {
	*x = EditorCommandResponse{}
	mi := &file_fetch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorCommandResponse) ProtoMessage() {}

func (x *EditorCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorCommandResponse.ProtoReflect.Descriptor instead.
func (*EditorCommandResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{13}
}

func (x *EditorCommandResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditorCommandResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorCommandResponse) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *EditorCommandResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EditorCommandResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EditorCommandResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditorCommandResponse) GetBeforePageStateId() string {
	if x != nil {
		return x.BeforePageStateId
	}
	return ""
}

func (x *EditorCommandResponse) GetAfterPageStateId() string {
	if x != nil {
		return x.AfterPageStateId
	}
	return ""
}

func (x *EditorCommandResponse) GetFinalUrl() string {
	if x != nil {
		return x.FinalUrl
	}
	return ""
}

func (x *EditorCommandResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *EditorCommandResponse) GetLocatorStrategy() string {
	if x != nil {
		return x.LocatorStrategy
	}
	return ""
}

func (x *EditorCommandResponse) GetLocatorExpression() string {
	if x != nil {
		return x.LocatorExpression
	}
	return ""
}

// Read-only page inspection; bounded JSON payloads share one versioned contract.
type EditorInspectionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	SessionId       string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PageStateId     string                 `protobuf:"bytes,4,opt,name=page_state_id,json=pageStateId,proto3" json:"page_state_id,omitempty"`
	Operation       string                 `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"` // inspect, dom, locator-check
	InputJson       string                 `protobuf:"bytes,6,opt,name=input_json,json=inputJson,proto3" json:"input_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditorInspectionRequest) Reset() {
	*x = EditorInspectionRequest{}
	mi := &file_fetch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorInspectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorInspectionRequest) ProtoMessage() {}

func (x *EditorInspectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorInspectionRequest.ProtoReflect.Descriptor instead.
func (*EditorInspectionRequest) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{14}
}

func (x *EditorInspectionRequest) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorInspectionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorInspectionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EditorInspectionRequest) GetPageStateId() string {
	if x != nil {
		return x.PageStateId
	}
	return ""
}

func (x *EditorInspectionRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *EditorInspectionRequest) GetInputJson() string {
	if x != nil {
		return x.InputJson
	}
	return ""
}

type EditorInspectionResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ProtocolVersion string                 `protobuf:"bytes,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	RequestId       string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Error           string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	ResultJson      string                 `protobuf:"bytes,6,opt,name=result_json,json=resultJson,proto3" json:"result_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditorInspectionResponse) Reset() {
	*x = EditorInspectionResponse{}
	mi := &file_fetch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorInspectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorInspectionResponse) ProtoMessage() {}

func (x *EditorInspectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorInspectionResponse.ProtoReflect.Descriptor instead.
func (*EditorInspectionResponse) Descriptor() ([]byte, []int) {
	return file_fetch_proto_rawDescGZIP(), []int{15}
}

func (x *EditorInspectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EditorInspectionResponse) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *EditorInspectionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EditorInspectionResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EditorInspectionResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EditorInspectionResponse) GetResultJson() string {
	if x != nil {
		return x.ResultJson
	}
	return ""
}

var File_fetch_proto protoreflect.FileDescriptor

const file_fetch_proto_rawDesc = "" +
	"\n" +
	"\vfetch.proto\x12\x04grpc\":\n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\x05R\atimeout\"S\n" +
	"\rFetchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x12\n" +
	"\x04html\x18\x02 \x01(\tR\x04html\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8c\x01\n" +
	"\rBrowserAction\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x16\n" +
	"\x06script\x18\x04 \x01(\tR\x06script\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x05R\ttimeoutMs\"\xa4\x03\n" +
	"\x11BrowserJobRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x18\n" +
	"\aprofile\x18\x04 \x01(\tR\aprofile\x12\x16\n" +
	"\x06recipe\x18\x05 \x01(\tR\x06recipe\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\x12-\n" +
	"\aactions\x18\a \x03(\v2\x13.grpc.BrowserActionR\aactions\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x12>\n" +
	"\aheaders\x18\t \x03(\v2$.grpc.BrowserJobRequest.HeadersEntryR\aheaders\x12\x1d\n" +
	"\n" +
	"close_page\x18\n" +
	" \x01(\bR\tclosePage\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\rBrowserCookie\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\"\x90\x01\n" +
	"\x13BrowserActionResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xfc\x03\n" +
	"\x12BrowserJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x12\n" +
	"\x04html\x18\x06 \x01(\tR\x04html\x12\x12\n" +
	"\x04text\x18\a \x01(\tR\x04text\x12\x12\n" +
	"\x04json\x18\b \x01(\tR\x04json\x12\x1e\n" +
	"\n" +
	"screenshot\x18\t \x01(\fR\n" +
	"screenshot\x12-\n" +
	"\acookies\x18\n" +
	" \x03(\v2\x13.grpc.BrowserCookieR\acookies\x12\x1f\n" +
	"\vduration_ms\x18\v \x01(\x03R\n" +
	"durationMs\x12\x1b\n" +
	"\tfinal_url\x18\f \x01(\tR\bfinalUrl\x12\x1f\n" +
	"\vstatus_code\x18\r \x01(\x05R\n" +
	"statusCode\x12!\n" +
	"\fcontent_type\x18\x0e \x01(\tR\vcontentType\x12@\n" +
	"\x0eaction_results\x18\x0f \x03(\v2\x19.grpc.BrowserActionResultR\ractionResults\"`\n" +
	"\x14BrowserHealthRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\x91\x01\n" +
	"\x15BrowserHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xb7\x02\n" +
	"\x1aEditorSessionCreateRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1f\n" +
	"\vttl_seconds\x18\x05 \x01(\x05R\n" +
	"ttlSeconds\x12%\n" +
	"\x0eviewport_width\x18\x06 \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\a \x01(\x05R\x0eviewportHeight\x12-\n" +
	"\x12authorization_json\x18\b \x01(\tR\x11authorizationJson\"\xc4\x01\n" +
	"\x14EditorSessionRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vttl_seconds\x18\x04 \x01(\x05R\n" +
	"ttlSeconds\x12\"\n" +
	"\rpage_state_id\x18\x05 \x01(\tR\vpageStateId\"\xc9\x03\n" +
	"\x15EditorSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\a \x01(\tR\x05error\x12+\n" +
	"\x12expires_at_unix_ms\x18\b \x01(\x03R\x0fexpiresAtUnixMs\x12\"\n" +
	"\rpage_state_id\x18\t \x01(\tR\vpageStateId\x12\x1f\n" +
	"\vcurrent_url\x18\n" +
	" \x01(\tR\n" +
	"currentUrl\x12%\n" +
	"\x0eviewport_width\x18\v \x01(\x05R\rviewportWidth\x12'\n" +
	"\x0fviewport_height\x18\f \x01(\x05R\x0eviewportHeight\x12\x1e\n" +
	"\n" +
	"screenshot\x18\r \x01(\fR\n" +
	"screenshot\"\xc2\x03\n" +
	"\x14EditorCommandRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x04 \x01(\tR\tcommandId\x12\"\n" +
	"\rpage_state_id\x18\x05 \x01(\tR\vpageStateId\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12)\n" +
	"\x10locator_strategy\x18\a \x01(\tR\x0flocatorStrategy\x12-\n" +
	"\x12locator_expression\x18\b \x01(\tR\x11locatorExpression\x12\x14\n" +
	"\x05value\x18\t \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\n" +
	" \x01(\x05R\ttimeoutMs\x12\x1c\n" +
	"\tconfirmed\x18\v \x01(\bR\tconfirmed\x12!\n" +
	"\fhas_position\x18\f \x01(\bR\vhasPosition\x12\f\n" +
	"\x01x\x18\r \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x0e \x01(\x01R\x01y\"\xc0\x03\n" +
	"\x15EditorCommandResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"command_id\x18\x03 \x01(\tR\tcommandId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x05 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12/\n" +
	"\x14before_page_state_id\x18\a \x01(\tR\x11beforePageStateId\x12-\n" +
	"\x13after_page_state_id\x18\b \x01(\tR\x10afterPageStateId\x12\x1b\n" +
	"\tfinal_url\x18\t \x01(\tR\bfinalUrl\x12\x1f\n" +
	"\vduration_ms\x18\n" +
	" \x01(\x03R\n" +
	"durationMs\x12)\n" +
	"\x10locator_strategy\x18\v \x01(\tR\x0flocatorStrategy\x12-\n" +
	"\x12locator_expression\x18\f \x01(\tR\x11locatorExpression\"\xe3\x01\n" +
	"\x17EditorInspectionRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\"\n" +
	"\rpage_state_id\x18\x04 \x01(\tR\vpageStateId\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x1d\n" +
	"\n" +
	"input_json\x18\x06 \x01(\tR\tinputJson\"\xd4\x01\n" +
	"\x18EditorInspectionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10protocol_version\x18\x02 \x01(\tR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\x12\x1f\n" +
	"\vresult_json\x18\x06 \x01(\tR\n" +
	"resultJson2\xbd\a\n" +
	"\x10PageFetchService\x120\n" +
	"\x05Fetch\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponse\x125\n" +
	"\n" +
	"FetchJavDB\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponse\x129\n" +
	"\x0eFetchSehuatang\x12\x12.grpc.FetchRequest\x1a\x13.grpc.FetchResponse\x12<\n" +
	"\aExecute\x12\x17.grpc.BrowserJobRequest\x1a\x18.grpc.BrowserJobResponse\x12A\n" +
	"\x06Health\x12\x1a.grpc.BrowserHealthRequest\x1a\x1b.grpc.BrowserHealthResponse\x12T\n" +
	"\x13CreateEditorSession\x12 .grpc.EditorSessionCreateRequest\x1a\x1b.grpc.EditorSessionResponse\x12K\n" +
	"\x10GetEditorSession\x12\x1a.grpc.EditorSessionRequest\x1a\x1b.grpc.EditorSessionResponse\x12Q\n" +
	"\x16HeartbeatEditorSession\x12\x1a.grpc.EditorSessionRequest\x1a\x1b.grpc.EditorSessionResponse\x12M\n" +
	"\x12CloseEditorSession\x12\x1a.grpc.EditorSessionRequest\x1a\x1b.grpc.EditorSessionResponse\x12M\n" +
	"\x12FrameEditorSession\x12\x1a.grpc.EditorSessionRequest\x1a\x1b.grpc.EditorSessionResponse\x12O\n" +
	"\x14ExecuteEditorCommand\x12\x1a.grpc.EditorCommandRequest\x1a\x1b.grpc.EditorCommandResponse\x12K\n" +
	"\x10GetEditorCommand\x12\x1a.grpc.EditorCommandRequest\x1a\x1b.grpc.EditorCommandResponse\x12R\n" +
	"\x11InspectEditorPage\x12\x1d.grpc.EditorInspectionRequest\x1a\x1e.grpc.EditorInspectionResponseB7Z5github.com/nekoimi/scrapio/internal/drission_rod/grpcb\x06proto3"

var (
	file_fetch_proto_rawDescOnce sync.Once
	file_fetch_proto_rawDescData []byte
)

func file_fetch_proto_rawDescGZIP() []byte {
	file_fetch_proto_rawDescOnce.Do(func() {
		file_fetch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fetch_proto_rawDesc), len(file_fetch_proto_rawDesc)))
	})
	return file_fetch_proto_rawDescData
}

var file_fetch_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_fetch_proto_goTypes = []any{
	(*FetchRequest)(nil),               // 0: grpc.FetchRequest
	(*FetchResponse)(nil),              // 1: grpc.FetchResponse
	(*BrowserAction)(nil),              // 2: grpc.BrowserAction
	(*BrowserJobRequest)(nil),          // 3: grpc.BrowserJobRequest
	(*BrowserCookie)(nil),              // 4: grpc.BrowserCookie
	(*BrowserActionResult)(nil),        // 5: grpc.BrowserActionResult
	(*BrowserJobResponse)(nil),         // 6: grpc.BrowserJobResponse
	(*BrowserHealthRequest)(nil),       // 7: grpc.BrowserHealthRequest
	(*BrowserHealthResponse)(nil),      // 8: grpc.BrowserHealthResponse
	(*EditorSessionCreateRequest)(nil), // 9: grpc.EditorSessionCreateRequest
	(*EditorSessionRequest)(nil),       // 10: grpc.EditorSessionRequest
	(*EditorSessionResponse)(nil),      // 11: grpc.EditorSessionResponse
	(*EditorCommandRequest)(nil),       // 12: grpc.EditorCommandRequest
	(*EditorCommandResponse)(nil),      // 13: grpc.EditorCommandResponse
	(*EditorInspectionRequest)(nil),    // 14: grpc.EditorInspectionRequest
	(*EditorInspectionResponse)(nil),   // 15: grpc.EditorInspectionResponse
	nil,                                // 16: grpc.BrowserJobRequest.HeadersEntry
}
var file_fetch_proto_depIdxs = []int32{
	2,  // 0: grpc.BrowserJobRequest.actions:type_name -> grpc.BrowserAction
	16, // 1: grpc.BrowserJobRequest.headers:type_name -> grpc.BrowserJobRequest.HeadersEntry
	4,  // 2: grpc.BrowserJobResponse.cookies:type_name -> grpc.BrowserCookie
	5,  // 3: grpc.BrowserJobResponse.action_results:type_name -> grpc.BrowserActionResult
	0,  // 4: grpc.PageFetchService.Fetch:input_type -> grpc.FetchRequest
	0,  // 5: grpc.PageFetchService.FetchJavDB:input_type -> grpc.FetchRequest
	0,  // 6: grpc.PageFetchService.FetchSehuatang:input_type -> grpc.FetchRequest
	3,  // 7: grpc.PageFetchService.Execute:input_type -> grpc.BrowserJobRequest
	7,  // 8: grpc.PageFetchService.Health:input_type -> grpc.BrowserHealthRequest
	9,  // 9: grpc.PageFetchService.CreateEditorSession:input_type -> grpc.EditorSessionCreateRequest
	10, // 10: grpc.PageFetchService.GetEditorSession:input_type -> grpc.EditorSessionRequest
	10, // 11: grpc.PageFetchService.HeartbeatEditorSession:input_type -> grpc.EditorSessionRequest
	10, // 12: grpc.PageFetchService.CloseEditorSession:input_type -> grpc.EditorSessionRequest
	10, // 13: grpc.PageFetchService.FrameEditorSession:input_type -> grpc.EditorSessionRequest
	12, // 14: grpc.PageFetchService.ExecuteEditorCommand:input_type -> grpc.EditorCommandRequest
	12, // 15: grpc.PageFetchService.GetEditorCommand:input_type -> grpc.EditorCommandRequest
	14, // 16: grpc.PageFetchService.InspectEditorPage:input_type -> grpc.EditorInspectionRequest
	1,  // 17: grpc.PageFetchService.Fetch:output_type -> grpc.FetchResponse
	1,  // 18: grpc.PageFetchService.FetchJavDB:output_type -> grpc.FetchResponse
	1,  // 19: grpc.PageFetchService.FetchSehuatang:output_type -> grpc.FetchResponse
	6,  // 20: grpc.PageFetchService.Execute:output_type -> grpc.BrowserJobResponse
	8,  // 21: grpc.PageFetchService.Health:output_type -> grpc.BrowserHealthResponse
	11, // 22: grpc.PageFetchService.CreateEditorSession:output_type -> grpc.EditorSessionResponse
	11, // 23: grpc.PageFetchService.GetEditorSession:output_type -> grpc.EditorSessionResponse
	11, // 24: grpc.PageFetchService.HeartbeatEditorSession:output_type -> grpc.EditorSessionResponse
	11, // 25: grpc.PageFetchService.CloseEditorSession:output_type -> grpc.EditorSessionResponse
	11, // 26: grpc.PageFetchService.FrameEditorSession:output_type -> grpc.EditorSessionResponse
	13, // 27: grpc.PageFetchService.ExecuteEditorCommand:output_type -> grpc.EditorCommandResponse
	13, // 28: grpc.PageFetchService.GetEditorCommand:output_type -> grpc.EditorCommandResponse
	15, // 29: grpc.PageFetchService.InspectEditorPage:output_type -> grpc.EditorInspectionResponse
	17, // [17:30] is the sub-list for method output_type
	4,  // [4:17] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_fetch_proto_init() }
func file_fetch_proto_init() {
	if File_fetch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fetch_proto_rawDesc), len(file_fetch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fetch_proto_goTypes,
		DependencyIndexes: file_fetch_proto_depIdxs,
		MessageInfos:      file_fetch_proto_msgTypes,
	}.Build()
	File_fetch_proto = out.File
	file_fetch_proto_goTypes = nil
	file_fetch_proto_depIdxs = nil
}
