<template>
  <div class="app-page"><div class="eyebrow">SCRAPIO / V2.2 / DRAFT</div><h1>{{ draft?.name || '采集方案' }}</h1><p class="lead">入口：{{ draft?.entry_url }} · revision {{ draft?.revision }}</p><section class="app-card"><label for="collector-name">方案名称</label><input id="collector-name" v-model="name" class="full-input" /><label for="collector-definition">定义 JSON</label><textarea id="collector-definition" v-model="definitionText" class="definition-editor" spellcheck="false" /><div class="editor-actions"><button :disabled="saving" @click="save(false)">{{ saving ? '保存中…' : '保存草稿' }}</button><button class="secondary-action" :disabled="!dirty || saving" @click="undoUnsaved">撤销未保存修改</button><button class="secondary-action" :disabled="saving || checking || dirty || !draft || !!conflictLatest" @click="validate">{{ checking ? '检查中…' : '检查草稿结构' }}</button><router-link to="/app/collectors">返回方案列表</router-link><span class="save-state" aria-live="polite">{{ saveState }}</span></div><p class="muted">草稿会自动保存；保存使用 revision 检查，冲突时本地编辑不会被覆盖。结构检查只验证当前定义格式，不访问目标网站。</p><div v-if="draft" class="validation-state" :data-state="draft.validation_status || 'not_validated'"><strong>结构检查：{{ validationLabel }}</strong><ul v-if="draft.validation_errors?.length"><li v-for="item in draft.validation_errors" :key="item">{{ item }}</li></ul></div><div v-if="conflictLatest" class="conflict-box" role="alert"><strong>服务器上的草稿已更新</strong><p>本地编辑仍保留在当前页面。加载服务器版本会用 revision {{ conflictLatest.revision }} 覆盖当前编辑内容。</p><button @click="loadLatest">加载服务器版本</button></div></section><p v-if="message" class="status-good">{{ message }}</p><p v-if="error" class="app-error" role="alert">{{ error }}</p></div>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { appApi, type Collector } from './api';
const route = useRoute(); const draft = ref<Collector>(); const name = ref(''); const definitionText = ref(''); const saving = ref(false); const checking = ref(false); const dirty = ref(false); const message = ref(''); const error = ref(''); const conflictLatest = ref<Collector>(); const saveState = ref('');
let saveTimer: ReturnType<typeof setTimeout> | undefined; let loaded = false; let suppressChanges = false; let savedName = ''; let savedDefinition = '';
const validationLabel = computed(() => ({ not_validated: '未检查', valid: '通过', invalid: '未通过', stale: '已过期' }[draft.value?.validation_status || 'not_validated']));
const changedFieldLabels: Record<string, string> = { name: '名称', entry_url: '入口地址', definition: '采集定义' };
function formatDefinition(value: Collector['definition']) { return JSON.stringify(value, null, 2); }
onMounted(async () => { try { draft.value = await appApi.collector(String(route.params.id)); name.value = draft.value.name; definitionText.value = formatDefinition(draft.value.definition); savedName = name.value; savedDefinition = definitionText.value; loaded = true; saveState.value = '已保存'; } catch { error.value = '无法读取草稿。'; } });
watch([name, definitionText], () => { if (!loaded || suppressChanges) return; dirty.value = true; message.value = ''; saveState.value = '有未保存修改'; if (conflictLatest.value) return; if (saveTimer) clearTimeout(saveTimer); saveTimer = setTimeout(() => save(true), 900); });
async function save(silent = false) { if (!draft.value || saving.value || !dirty.value || conflictLatest.value) return; let definition: Record<string, any>; try { definition = JSON.parse(definitionText.value); if (!definition || Array.isArray(definition) || typeof definition !== 'object') throw new Error('object required'); } catch { error.value = '定义必须是有效的 JSON 对象；修改暂留在本地。'; saveState.value = '等待修正'; return; } saving.value = true; error.value = ''; const sentName = name.value; const sentDefinition = definitionText.value; saveState.value = '保存中…'; try { draft.value = await appApi.updateCollector(draft.value.id, { name: sentName, expected_revision: draft.value.revision, definition }); savedName = sentName; savedDefinition = sentDefinition; dirty.value = name.value !== sentName || definitionText.value !== sentDefinition; saveState.value = dirty.value ? '还有修改待保存' : '已保存'; if (!dirty.value) { const summary = draft.value.save_summary; const fields = (summary?.changed_fields || []).map(field => changedFieldLabels[field] || field); message.value = summary ? `已保存 revision ${summary.revision}${fields.length ? `，更新：${fields.join('、')}` : '，内容未变化'}` : `已保存 revision ${draft.value.revision}`; } } catch (cause: any) { const latest = cause?.error?.latest as Collector | undefined; if (latest) { conflictLatest.value = latest; saveState.value = '存在版本冲突'; error.value = '服务器版本已变化，本地修改仍保留。'; } else { error.value = '草稿保存失败，本地修改仍保留。'; saveState.value = '保存失败'; } } finally { saving.value = false; if (dirty.value && !conflictLatest.value && !error.value) { if (saveTimer) clearTimeout(saveTimer); saveTimer = setTimeout(() => save(true), 900); } else if (!silent && dirty.value && !conflictLatest.value && error.value) { saveState.value = '保存失败'; } } }
async function validate() { if (!draft.value || dirty.value || checking.value || saving.value || conflictLatest.value) return; checking.value = true; error.value = ''; try { const response = await appApi.validateCollector(draft.value.id); draft.value = response.collector; message.value = response.validation.valid ? '当前草稿结构检查通过；尚未访问目标网站。' : '草稿结构检查未通过，请按错误提示修正。'; } catch { error.value = '结构检查失败，请稍后重试。'; } finally { checking.value = false; } }
function undoUnsaved() { suppressChanges = true; name.value = savedName; definitionText.value = savedDefinition; dirty.value = false; if (saveTimer) clearTimeout(saveTimer); error.value = ''; message.value = ''; saveState.value = '已撤销未保存修改'; queueMicrotask(() => { suppressChanges = false; }); }
function loadLatest() { if (!conflictLatest.value) return; suppressChanges = true; draft.value = conflictLatest.value; name.value = draft.value.name; definitionText.value = formatDefinition(draft.value.definition); savedName = name.value; savedDefinition = definitionText.value; dirty.value = false; conflictLatest.value = undefined; error.value = ''; saveState.value = '已加载服务器版本'; queueMicrotask(() => { suppressChanges = false; }); }
onBeforeUnmount(() => { if (saveTimer) clearTimeout(saveTimer); });
</script>
