<template>
 <div class="v21-stack">
  <header class="v21-header"><div><div class="v21-eyebrow">Workspace / 数据</div><h1>数据集与记录</h1><p>按目标数据查询结果，并追溯每条记录的来源、运行和原文。</p></div><el-button type="primary" :disabled="!projectId" @click="openCreate">新建数据集</el-button></header>
  <p v-if="error" class="v21-error" role="alert">{{error}}</p>
  <div class="v21-grid two"><section class="v21-card"><h2>数据集</h2><div v-if="loading" class="v21-empty">加载中…</div><div v-else-if="!datasets.length" class="v21-empty">当前项目还没有数据集。创建后即可为采集器定义目标字段。</div><button v-for="item in datasets" :key="item.id" class="dataset-item" :class="{active:item.id===selected}" @click="choose(item.id)"><span><strong>{{item.name}}</strong><small>{{item.record_type}} · Schema v{{item.schema_version}}</small></span><span>→</span></button></section><section class="v21-card"><div class="records-head"><h2>{{current?.name||'字段结构'}}</h2><el-button v-if="current" :disabled="schemaLoading" @click="openEdit">修改字段结构</el-button></div><div v-if="!current" class="v21-empty">选择一个数据集查看字段结构。</div><template v-else><div class="v21-field"><label for="schema-version">Schema 版本</label><select id="schema-version" v-model.number="schemaVersion" :disabled="schemaLoading" @change="loadSchema"><option v-for="item in current.schema_version" :key="item" :value="item">v{{item}}{{item===current.schema_version?' · 当前':''}}</option></select></div><div v-if="schemaLoading" class="v21-empty">正在加载字段…</div><template v-else-if="viewedSchema"><div class="v21-note">唯一键：{{keyNames.join(' + ')||'未定义'}} · 空值策略：{{viewedSchema.empty_value_policy==='preserve'?'保留已有值':'允许覆盖'}}</div><p v-if="schemaVersion!==current.schema_version" class="v21-muted">正在查看历史字段定义。下方记录仍显示当前保存的数据。</p><div v-for="field in fields" :key="field.field_key" class="v21-row"><div><strong>{{field.label}}</strong><small>{{field.field_key}} · {{field.field_type}}{{field.multiple?'[]':''}}</small></div><span v-if="field.required" class="v21-status">必填</span></div></template></template></section></div>
  <section class="v21-card"><div class="records-head"><div><h2>记录 · {{total}}</h2><span class="v21-muted">{{current?.name||'请选择数据集'}}</span></div><div class="v21-actions"><el-button :disabled="!selected" @click="saveCurrentView">保存当前筛选</el-button><el-button :disabled="!selected||exportBusy" @click="exportRecords">导出 CSV</el-button></div></div>
   <div v-if="selected" class="filter-grid"><div class="v21-field"><label>搜索唯一键或字段</label><input v-model="query" placeholder="搜索整个数据集" @keyup.enter="applyFilters" /></div><div class="v21-field"><label>来源</label><select v-model.number="sourceId"><option :value="0">全部来源</option><option v-for="source in coverage" :key="source.source_id" :value="source.source_id||-1">{{source.source_name}}</option></select></div><div class="v21-field"><label>变化类型</label><select v-model="activity"><option value="">全部记录</option><option value="created">新增</option><option value="updated">变化</option></select></div><div class="v21-field"><label>起始日期</label><input v-model="sinceDate" type="date" /></div><el-button @click="applyFilters">查询</el-button></div>
   <div v-if="selected" class="v21-actions"><span class="v21-muted">常用视图：</span><button v-for="view in views" :key="view.id" class="v21-link text-button" @click="useView(view)">{{view.name}}</button><el-button v-if="activeView" text type="danger" @click="deleteCurrentView">删除视图</el-button></div>
   <div v-if="exportJob" class="v21-note">后台导出 #{{exportJob.id}} · {{exportJob.status}} · {{exportJob.row_count}} 条 <span v-if="exportJob.error">{{exportJob.error}}</span><el-button v-if="exportJob.status==='ready'" text @click="downloadExport">下载</el-button><el-button v-else-if="exportJob.status==='queued'||exportJob.status==='running'" text @click="refreshExport">刷新状态</el-button></div>
   <div v-if="!selected" class="v21-empty">选择数据集后查看采集结果。</div><div v-else-if="!records.length" class="v21-empty">暂无匹配记录。调整筛选条件或运行采集器。</div><div v-else class="v21-table-wrap"><table class="v21-table"><thead><tr><th>唯一键</th><th>字段摘要</th><th>最近变化</th><th>来源</th><th>最近发现</th><th>操作</th></tr></thead><tbody><tr v-for="row in records" :key="row.id"><td>{{row.canonical_key}}</td><td>{{summary(row)}}</td><td>{{row.last_decision==='created'?'新增':row.last_decision==='updated'?'变化':'—'}} · {{formatDate(row.last_changed_at)}}</td><td>{{row.source_count}}</td><td>{{formatDate(row.last_seen_at)}}</td><td><button class="v21-link text-button" @click="openRecord(row.id)">字段与来源 →</button></td></tr></tbody></table></div><div class="pager"><el-button :disabled="page<=1" @click="page--;loadRecords()">上一页</el-button><span>第 {{page}} 页</span><el-button :disabled="page*20>=total" @click="page++;loadRecords()">下一页</el-button></div></section>
  <section v-if="selected" class="v21-card"><h2>来源覆盖</h2><div v-if="!coverage.length" class="v21-empty">尚无来源观察。</div><div v-for="source in coverage" :key="source.source_id" class="v21-row"><div><strong>{{source.source_name}}</strong><small>最近观察 {{formatDate(source.last_observed_at)}}</small></div><span>{{source.records}} 条记录 · {{source.observations}} 次观察</span></div></section>
  <el-drawer v-model="recordDrawer" size="min(620px,96vw)" title="记录与来源"><div v-if="detail"><h2>{{detail.record.canonical_key}}</h2><p class="v21-muted">首次发现 {{formatDate(detail.record.first_seen_at)}} · 最近发现 {{formatDate(detail.record.last_seen_at)}}</p><h3>当前字段</h3><dl class="facts"><template v-for="(value,key) in jsonValue(detail.record.normalized)" :key="key"><dt>{{key}}</dt><dd>{{display(value)}}</dd></template></dl><h3>来源证据</h3><div v-if="!detail.observations?.length" class="v21-empty">暂无来源观察。</div><div v-for="ob in detail.observations" :key="ob.id" class="v21-row"><div><strong>{{ob.decision}} · {{formatDate(ob.observed_at)}}</strong><small>采集器 #{{ob.workflow_id||'—'}} · 版本 #{{ob.workflow_version_id||'—'}} · Schema v{{ob.schema_version}}</small><a v-if="ob.source_url" :href="ob.source_url" target="_blank" rel="noopener noreferrer" class="v21-link">来源页面 ↗</a></div><div><router-link v-if="ob.run_id" class="v21-link" :to="{path:'/workspace/runs',query:{id:String(ob.run_id)}}">查看运行</router-link><br><button v-if="ob.document_id" class="v21-link text-button" @click="showDocument(ob.document_id)">原始文档</button></div></div><h3>字段修订</h3><div v-for="rev in detail.revisions" :key="rev.id" class="v21-row"><span>{{formatDate(rev.created_at)}}</span><span>{{display(jsonValue(rev.changed_fields))}}</span></div></div></el-drawer>
  <el-dialog v-model="documentDialog" title="原始文档" width="min(900px,96vw)"><pre class="document-content">{{documentContent}}</pre></el-dialog>
  <el-dialog v-model="dialog" :title="editingDataset?'更新数据集 Schema':'新建数据集'" width="min(780px,96vw)" :close-on-click-modal="false">
   <div v-if="!editingDataset" class="form-pair"><div class="v21-field"><label for="dataset-name">数据集名称</label><input id="dataset-name" v-model="form.name" placeholder="例如：文章" /></div><div class="v21-field"><label for="dataset-code">标识</label><input id="dataset-code" v-model="form.code" placeholder="例如：article" /></div><div class="v21-field"><label for="dataset-type">记录类型</label><input id="dataset-type" v-model="form.record_type" placeholder="例如：article" /></div></div>
   <p v-else class="v21-note">{{editingDataset.name}} · 基于当前 Schema v{{editingDataset.schema_version}} 创建新版本，历史定义保留。采集器的新草稿须按新 Schema 重新预览和发布。</p>
   <SchemaEditor :model="form" />
   <template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveDataset">{{editingDataset?'保存新版本':'创建数据集'}}</el-button></template>
  </el-dialog>
 </div>
</template>
<script setup lang="ts">
import { computed,onMounted,onUnmounted,reactive,ref,watch } from 'vue';
import { useRoute } from 'vue-router';
import { ElMessage } from 'element-plus';
import { api,errorText,jsonValue,type Dataset,type DatasetField,type DatasetSchema,type ExportJob,type RecordFilter,type RecordRow,type SavedView,type SourceCoverage } from './api';
import { projectId } from './state';
import SchemaEditor from './schema-editor.vue';
const route=useRoute();
const all=ref<Dataset[]>([]),fields=ref<DatasetField[]>([]),records=ref<RecordRow[]>([]),selected=ref(0),page=ref(1),total=ref(0),query=ref(''),sourceId=ref(0),activity=ref('' as RecordFilter['activity']),sinceDate=ref(''),coverage=ref<SourceCoverage[]>([]),views=ref<SavedView[]>([]),activeView=ref(0),exportJob=ref<ExportJob|null>(null),exportBusy=ref(false),loading=ref(false),saving=ref(false),error=ref(''),dialog=ref(false),recordDrawer=ref(false),documentDialog=ref(false),detail=ref<any>(null),documentContent=ref('');
const schemaVersion=ref(1),viewedSchema=ref<Dataset|null>(null),schemaLoading=ref(false),editingDataset=ref<Dataset|null>(null);
const form=reactive<DatasetSchema & {code:string;name:string;record_type:string}>({code:'',name:'',record_type:'',empty_value_policy:'preserve',unique_key_fields:[],fields:[]});
const datasets=computed(()=>all.value.filter(d=>d.project_id===projectId.value));const current=computed(()=>datasets.value.find(d=>d.id===selected.value));
function parseKeys(value:Dataset['unique_key_fields']):string[]{const parsed=Array.isArray(value)?value:jsonValue(value);return Array.isArray(parsed)?parsed:[];}
const keyNames=computed(()=>viewedSchema.value?parseKeys(viewedSchema.value.unique_key_fields):[]);

function formatDate(value?:string){return value?new Date(value).toLocaleString():'—';}function display(value:any){return typeof value==='string'?value:JSON.stringify(value);}function summary(row:RecordRow){return Object.entries(jsonValue(row.normalized)).filter(([key])=>key!=='url'&&key!=='canonical_key').slice(0,3).map(([key,value])=>`${key}: ${display(value)}`).join(' · ')||'—';}
let loadRequest=0,schemaRequest=0,recordsRequest=0;
async function load(){const requestId=++loadRequest,ownerProject=projectId.value;loading.value=true;error.value='';try{const rows=await api.datasets(ownerProject);if(requestId!==loadRequest||ownerProject!==projectId.value)return;all.value=rows;const fromRoute=Number(route.query.dataset)||0;const id=datasets.value.some(d=>d.id===fromRoute)?fromRoute:datasets.value.some(d=>d.id===selected.value)?selected.value:datasets.value[0]?.id||0;await choose(id);}catch(e){if(requestId===loadRequest)error.value=errorText(e);}finally{if(requestId===loadRequest)loading.value=false;}}
async function choose(id:number){if(id&&!datasets.value.some(d=>d.id===id))return;selected.value=id;page.value=1;query.value='';sourceId.value=0;activity.value='';sinceDate.value='';activeView.value=0;coverage.value=[];views.value=[];exportJob.value=null;fields.value=[];viewedSchema.value=null;records.value=[];total.value=0;recordDrawer.value=false;schemaVersion.value=current.value?.schema_version||1;await Promise.all([loadSchema(),loadRecords(),loadExtras(id)]);}
async function loadSchema(){const id=selected.value,requestedVersion=schemaVersion.value,requestId=++schemaRequest;fields.value=[];viewedSchema.value=null;if(!id){schemaLoading.value=false;return;}schemaLoading.value=true;try{const result=await api.dataset(id,requestedVersion);if(requestId!==schemaRequest||selected.value!==id)return;viewedSchema.value=result.dataset;fields.value=result.fields||[];}catch(e){if(requestId===schemaRequest)error.value=errorText(e);}finally{if(requestId===schemaRequest)schemaLoading.value=false;}}
async function loadRecords(){const id=selected.value,requestId=++recordsRequest;if(!id)return;try{const response=await api.records(currentFilter(),page.value);if(requestId!==recordsRequest||selected.value!==id)return;records.value=response.list||[];total.value=response.total||0;}catch(e){if(requestId===recordsRequest)error.value=errorText(e);}}
function currentFilter():RecordFilter{return {dataset_id:selected.value,query:query.value.trim(),source_id:sourceId.value||undefined,activity:activity.value||undefined,since:sinceDate.value?new Date(`${sinceDate.value}T00:00:00`).toISOString():undefined};}
function applyFilters(){activeView.value=0;page.value=1;loadRecords();}
async function loadExtras(id:number){if(!id)return;try{const [sources,saved]=await Promise.all([api.recordCoverage(id),api.recordViews(id)]);if(selected.value!==id)return;coverage.value=sources||[];views.value=saved||[];}catch(e){error.value=errorText(e);}}
function useView(view:SavedView){query.value=view.filter.query||'';sourceId.value=view.filter.source_id||0;activity.value=view.filter.activity||'';sinceDate.value=view.filter.since?view.filter.since.slice(0,10):'';activeView.value=view.id;page.value=1;loadRecords();}
async function saveCurrentView(){const name=window.prompt('视图名称');if(!name?.trim())return;try{const saved=await api.saveRecordView(selected.value,name.trim(),currentFilter());await loadExtras(selected.value);activeView.value=saved.id;ElMessage.success('视图已保存');}catch(e){ElMessage.error(errorText(e));}}
async function deleteCurrentView(){if(!activeView.value)return;try{await api.deleteRecordView(selected.value,activeView.value);activeView.value=0;await loadExtras(selected.value);ElMessage.success('视图已删除');}catch(e){ElMessage.error(errorText(e));}}
function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function exportRecords(){exportBusy.value=true;try{if(total.value<=1000){saveBlob(await api.exportDirect(currentFilter()),`dataset-${selected.value}.csv`);return;}exportJob.value=await api.exportCreate(currentFilter());ElMessage.success('后台导出已创建');}catch(e){ElMessage.error(errorText(e));}finally{exportBusy.value=false;}}
async function refreshExport(){if(!exportJob.value)return;try{const result=await api.exportStatus(exportJob.value.id);if(result.dataset_id===selected.value)exportJob.value=result;}catch(e){ElMessage.error(errorText(e));}}
async function downloadExport(){if(!exportJob.value)return;try{saveBlob(await api.exportDownload(exportJob.value.id),`dataset-${selected.value}.csv`);}catch(e){ElMessage.error(errorText(e));}}
async function openRecord(id:number){const datasetId=selected.value;try{const result=await api.record(id);if(datasetId!==selected.value)return;if(result.record?.dataset_id!==datasetId)throw new Error('记录不属于当前数据集');detail.value=result;recordDrawer.value=true;}catch(e){ElMessage.error(errorText(e));}}
async function showDocument(id:number){try{const response=await api.document(id);documentContent.value=response.document?.content||'';documentDialog.value=true;}catch(e){ElMessage.error(errorText(e));}}
function openCreate(){editingDataset.value=null;Object.assign(form,{code:'',name:'',record_type:'',empty_value_policy:'preserve',unique_key_fields:[],fields:[{key:'url',label:'URL',type:'url',required:true,multiple:false}]});dialog.value=true;}
async function openEdit(){if(!current.value)return;const id=current.value.id;try{const result=await api.dataset(id);if(id!==selected.value)return;editingDataset.value=result.dataset;Object.assign(form,{code:result.dataset.code,name:result.dataset.name,record_type:result.dataset.record_type,empty_value_policy:result.dataset.empty_value_policy,unique_key_fields:parseKeys(result.dataset.unique_key_fields),fields:result.fields.map(f=>({key:f.field_key,label:f.label,type:f.field_type,required:f.required,multiple:f.multiple}))});dialog.value=true;}catch(e){ElMessage.error(errorText(e));}}
async function saveDataset(){if(!form.name.trim()||!form.code.trim()||!form.record_type.trim()||!form.unique_key_fields.length){ElMessage.warning('请填写名称、标识、类型和唯一键');return;}const ownerProject=projectId.value;saving.value=true;try{if(editingDataset.value){const latest=await api.dataset(editingDataset.value.id);if(latest.dataset.schema_version!==editingDataset.value.schema_version)throw new Error('Schema 已被更新，请重新打开编辑');}const row=editingDataset.value?await api.updateSchema(editingDataset.value.id,form):await api.createDataset({...form,project_id:ownerProject});dialog.value=false;if(ownerProject!==projectId.value)return;const rows=await api.datasets(ownerProject);if(ownerProject!==projectId.value)return;all.value=rows;await choose(row.id);ElMessage.success(editingDataset.value?'Schema 新版本已保存':'数据集已创建');}catch(e){ElMessage.error(errorText(e));}finally{saving.value=false;}}
onUnmounted(()=>{loadRequest++;schemaRequest++;recordsRequest++;});
watch(projectId,()=>{detail.value=null;recordDrawer.value=false;documentDialog.value=false;dialog.value=false;selected.value=0;load();});watch(()=>route.query.dataset,load);onMounted(load);
</script>
<style scoped>.dataset-item{width:100%;border:0;border-top:1px solid var(--v21-line);background:#fff;display:flex;align-items:center;justify-content:space-between;padding:14px 8px;text-align:left;cursor:pointer;color:var(--v21-ink)}.dataset-item.active,.dataset-item:hover{background:#eff3fb}.dataset-item strong,.dataset-item small{display:block}.dataset-item small{color:var(--v21-muted)}.records-head,.fields-title{display:flex;align-items:center;justify-content:space-between;gap:15px;margin-bottom:15px}.records-head h2{margin:0}.pager{display:flex;justify-content:flex-end;align-items:center;gap:12px;padding-top:16px}.facts{display:grid;grid-template-columns:150px minmax(0,1fr);gap:0}.facts dt,.facts dd{padding:9px;margin:0;border-bottom:1px solid var(--v21-line);word-break:break-word}.facts dt{font-weight:700;color:var(--v21-muted)}.text-button{border:0;background:transparent;padding:0}.document-content{white-space:pre-wrap;word-break:break-all;max-height:65vh;overflow:auto;background:#f5f7fb;padding:16px}.form-pair{display:grid;grid-template-columns:1fr 1fr;gap:0 15px}.field-editor{display:grid;grid-template-columns:1fr 1fr 105px 65px 65px 45px;gap:6px;align-items:center;margin-bottom:7px}.field-editor input:not([type=checkbox]),.field-editor select{min-width:0;border:1px solid #cfd8e4;border-radius:7px;padding:8px}.field-editor label{font-size:12px;white-space:nowrap}@media(max-width:760px){.form-pair{grid-template-columns:1fr}.field-editor{grid-template-columns:1fr 1fr 100px}.field-editor>*{min-width:0}} .filter-grid{display:grid;grid-template-columns:2fr 1fr 1fr 1fr auto;gap:10px;align-items:end;margin:15px 0}.filter-grid .v21-field{margin:0}@media(max-width:900px){.filter-grid{grid-template-columns:1fr 1fr}}@media(max-width:550px){.filter-grid{grid-template-columns:1fr}} </style>
