<template>
 <div class="v21-stack">
  <header class="v21-header"><div><div class="v21-eyebrow">Workspace / 运行中心</div><h1>运行记录</h1><p>查看访问、发现、保存决策和失败页面，逐层检查执行尝试与原文。</p></div><el-button @click="load">刷新</el-button></header>
  <p v-if="error" class="v21-error" role="alert">{{error}}</p>
  <div class="run-layout">
   <section class="v21-card run-list"><div class="section-head"><h2>最近运行</h2><small>{{total}} 次</small></div><div v-if="!runs.length" class="v21-empty">当前项目还没有运行。</div>
    <button v-for="run in runs" :key="run.id" class="run-item" :class="{active:selectedId===run.id}" @click="select(run.id)"><span><strong>{{workflowName(run.workflow_id)}}</strong><small>#{{run.id}} · {{date(run.created_at)}} · {{triggerName(run.trigger_type)}}</small></span><span class="v21-status" :class="statusClass(run.status)">{{statusName(run.status)}}</span></button>
    <div class="pager"><el-button :disabled="page<=1" @click="changePage(page-1)">上一页</el-button><span>{{page}} / {{Math.max(1,Math.ceil(total/20))}}</span><el-button :disabled="page*20>=total" @click="changePage(page+1)">下一页</el-button></div>
   </section>
   <section class="v21-card run-detail"><div v-if="!detail" class="v21-empty">选择一次运行查看页面树和结果。</div><template v-else>
    <div class="section-head"><div><div class="v21-eyebrow">{{workflowName(detail.run.workflow_id)}} / v#{{detail.run.workflow_version_id}}</div><h2>运行 #{{detail.run.id}}</h2><span class="v21-status" :class="statusClass(detail.run.status)">{{statusName(detail.run.status)}}</span></div><small>{{date(detail.run.created_at)}}</small></div>
    <p class="v21-muted">{{triggerName(detail.run.trigger_type)}}触发 · 开始 {{date(detail.run.started_at)}} · 结束 {{date(detail.run.finished_at)}}</p>
    <div class="metrics"><div v-for="metric in metrics" :key="metric.label" class="v21-note"><strong>{{metric.value}}</strong><small>{{metric.label}}</small></div></div>
    <div v-if="['partial','limited','failed'].includes(detail.run.status)" class="v21-note run-reason"><strong>{{statusExplanation(detail.run.status)}}</strong><span v-if="detail.inspection.stop_reasons.length">终止原因：{{detail.inspection.stop_reasons.join('、')}}</span><span v-if="detail.inspection.last_error">最近失败：{{detail.inspection.last_error}}</span></div>
    <div class="section-head"><h3>页面任务树 · {{taskTotal}}</h3><small>按创建顺序分批加载</small></div><div v-if="!tasks.length" class="v21-empty">暂无页面任务。</div>
    <button v-for="task in taskTree" :key="task.id" class="task-item" :class="{active:activeTask?.id===task.id}" :style="{paddingLeft:String(10+Math.min(task.treeDepth,8)*15)+'px'}" @click="selectTask(task)"><span><strong>{{taskLabel(task)}} · #{{task.id}}</strong><small>{{taskURL(task)}} · {{task.attempt_count}} 次尝试<span v-if="task.parent_task_id"> · 上级 #{{task.parent_task_id}}</span></small><small v-if="task.error_message">{{task.error_message}}</small></span><span class="v21-status" :class="statusClass(task.status)">{{statusName(task.status)}}</span></button>
    <div class="pager" v-if="tasks.length<taskTotal"><el-button :loading="tasksBusy" @click="loadMoreTasks">加载更多页面（{{tasks.length}} / {{taskTotal}}）</el-button></div>
    <div v-if="detail.limit_events?.length"><h3>限制事件</h3><div v-for="event in detail.limit_events" :key="event.task_id+'-'+event.reason+'-'+event.url" class="v21-row"><span>{{event.reason}} · {{event.page_role}} · #{{event.task_id}}</span><small>{{event.url}}</small></div></div>
    <router-link class="v21-link" :to="{path:'/workspace/collectors',query:{id:String(detail.run.workflow_id),version:String(detail.run.workflow_version_id)}}">查看运行时版本 →</router-link>
   </template></section>
   <aside class="v21-card inspect"><div class="v21-eyebrow">PAGE INSPECTOR</div><h2>页面检查</h2><div v-if="!activeTask" class="v21-empty">选择一个页面任务。</div><template v-else>
    <div class="v21-row"><strong>阶段</strong><span>{{taskLabel(activeTask)}}</span></div><div class="v21-row"><strong>状态</strong><span class="v21-status" :class="statusClass(activeTask.status)">{{statusName(activeTask.status)}}</span></div><div class="v21-row"><strong>页面</strong><span class="wrap">{{taskURL(activeTask)}}</span></div><p v-if="activeTask.error_message" class="v21-error">{{activeTask.error_message}}</p>
    <div class="inspect-tabs"><button :class="{active:inspectTab==='attempts'}" @click="inspectTab='attempts'">执行尝试</button><button :class="{active:inspectTab==='evidence'}" @click="inspectTab='evidence'">输入与原文</button></div>
    <template v-if="inspectTab==='attempts'"><div v-if="attemptsBusy" class="v21-muted">正在读取尝试…</div><div v-else-if="!attempts.length" class="v21-empty">尚未执行。</div><div v-for="attempt in attempts" :key="attempt.id" class="attempt"><div class="v21-row"><strong>第 {{attempt.attempt_no}} 次 · {{statusName(attempt.status)}}</strong><small>{{attempt.duration_ms}} ms</small></div><small>{{date(attempt.started_at)}} → {{date(attempt.finished_at)}}</small><p v-if="stage(attempt)" class="v21-note">失败阶段：{{stage(attempt)}}</p><p v-if="attempt.error_message" class="v21-error">{{attempt.error_message}}</p><div v-if="attempt.status==='succeeded'" class="v21-note">发现 {{snapshot(attempt).discovered_count||0}} · 候选 {{snapshot(attempt).record_count||0}} · {{snapshot(attempt).stop_reason||'正常结束'}}</div><details><summary>请求与结果快照</summary><pre class="json-box">{{pretty(attempt.request_snapshot)}}</pre><pre class="json-box">{{pretty(attempt.response_snapshot)}}</pre></details></div><el-button v-if="attempts.length<attemptTotal" text :loading="attemptsBusy" @click="loadMoreAttempts()">更多尝试</el-button></template>
    <template v-else><h3>任务输入</h3><pre class="json-box">{{pretty(activeTask.input)}}</pre><div v-if="!activeTask.output_document_id" class="v21-note">此页面没有保存原文，可能在获取或预算阶段终止。</div><template v-else><el-button :loading="documentBusy" @click="loadDocument(activeTask.output_document_id!)">{{document?'重新读取':'读取原文与截图'}}</el-button><template v-if="document"><h3>原文 #{{document.document.id}}</h3><small>{{document.document.document_type}} · {{document.document.content_size}} bytes</small><pre class="document-box">{{document.document.content}}</pre><div v-for="asset in document.assets" :key="asset.id"><h3>{{asset.asset_type}} · {{asset.content_size}} bytes</h3><img v-if="asset.asset_type==='screenshot'&&asset.content" class="screenshot" :src="'data:'+asset.content_type+';base64,'+asset.content" alt="页面截图" /></div></template></template></template>
    <div class="inspect-actions"><router-link v-if="detail" class="v21-link" :to="repairRoute">用此页面制作修复样例 →</router-link><router-link v-if="detail" class="v21-link" :to="{path:'/workspace/collectors',query:{id:String(detail.run.workflow_id)}}">打开采集器 →</router-link></div>
   </template></aside>
  </div>
 </div>
</template>
<script setup lang="ts">
import {computed,onMounted,ref,watch} from 'vue';
import {useRoute,useRouter} from 'vue-router';
import {ElMessage} from 'element-plus';
import {api,errorText,jsonValue,workflowPages,type DocumentDetail,type Run,type RunDetail,type Task,type TaskAttempt,type Workflow} from './api';
import {projectId} from './state';
const route=useRoute(),router=useRouter();
const allWorkflows=ref<Workflow[]>([]),allRuns=ref<Run[]>([]),detail=ref<RunDetail|null>(null),tasks=ref<Task[]>([]),taskTotal=ref(0),taskPage=ref(0),tasksBusy=ref(false),activeTask=ref<Task|null>(null),attempts=ref<TaskAttempt[]>([]),attemptTotal=ref(0),attemptPage=ref(0),attemptsBusy=ref(false),document=ref<DocumentDetail|null>(null),documentBusy=ref(false),inspectTab=ref<'attempts'|'evidence'>('attempts'),selectedId=ref(0),page=ref(1),total=ref(0),error=ref('');
const workflows=computed(()=>allWorkflows.value.filter(w=>w.project_id===projectId.value));const runs=computed(()=>allRuns.value.filter(r=>workflows.value.some(w=>w.id===r.workflow_id)));
const metrics=computed(()=>{const v=detail.value?.inspection;return v?[{label:'已访问页面',value:v.pages_visited},{label:'发现链接',value:v.discovered},{label:'候选记录',value:v.candidates},{label:'新增',value:v.created},{label:'变化',value:v.updated},{label:'未变',value:v.unchanged},{label:'失败页面',value:v.pages_failed},{label:'受限页面',value:v.pages_limited}]:[];});
const taskTree=computed(()=>{const byID=new Map(tasks.value.map(t=>[t.id,t]));return tasks.value.map(task=>{let depth=0,parent=task.parent_task_id,seen=new Set<number>();while(parent&&byID.has(parent)&&!seen.has(parent)){seen.add(parent);depth++;parent=byID.get(parent)?.parent_task_id}return {...task,treeDepth:Math.max(depth,task.depth||0)};});});
const repairRoute=computed(()=>({path:'/workspace/collectors',query:{id:String(detail.value?.run.workflow_id||0),repair_task:String(activeTask.value?.id||0),repair_document:activeTask.value?.output_document_id?String(activeTask.value.output_document_id):undefined,repair_role:activeTask.value?.step_name==='detail'?'detail':activeTask.value?.step_name==='list'||jsonValue(activeTask.value?.input).page_role==='list'?'list':'trigger',repair_url:activeTask.value?taskURL(activeTask.value):undefined}}));
function workflowName(id:number){return allWorkflows.value.find(w=>w.id===id)?.name||'采集器 #'+id;}function date(value?:string){return value?new Date(value).toLocaleString():'—';}function pretty(value:any){return JSON.stringify(jsonValue(value),null,2);}function taskURL(task:Task){return jsonValue(task.input).url||'使用采集器入口 URL';}
function triggerName(value:string){return ({manual:'手动',cron:'定时',api:'API'} as Record<string,string>)[value]||value;}
function statusName(value:string){return ({queued:'排队',running:'运行中',succeeded:'成功',completed:'成功',partial:'部分成功',limited:'受限结束',failed:'失败',dead_letter:'失败',cancelled:'已取消',interrupted:'已中断'} as Record<string,string>)[value]||value;}
function statusClass(value:string){return ['succeeded','completed'].includes(value)?'ok':['failed','dead_letter','cancelled'].includes(value)?'bad':'warn';}
function statusExplanation(value:string){return ({partial:'部分页面或步骤失败，已有结果仍保留。',limited:'达到运行预算，已保存的结果保留。',failed:'运行未得到有效结果，请检查失败页面。'} as Record<string,string>)[value]||'';}
function taskLabel(task:Task){if(task.step_name==='detail')return '详情页';if(task.step_name==='list')return '分页列表 · 第 '+(jsonValue(task.input).page_index||'?')+' 页';if(task.step_name==='trigger'&&jsonValue(task.input).page_role==='list')return '入口列表';return task.step_name==='trigger'?'入口页面':task.step_name;}
function snapshot(attempt:TaskAttempt){return jsonValue(attempt.response_snapshot);}function stage(attempt:TaskAttempt){return snapshot(attempt).stage||'';}
let selection=0,taskSelection=0,taskRequest=0,attemptRequest=0,documentRequest=0;
async function changePage(next:number){page.value=next;await router.replace({path:'/workspace/runs'});await load();}
async function load(){const marker=++selection;error.value='';detail.value=null;tasks.value=[];activeTask.value=null;document.value=null;try{const id=projectId.value;const [w,r]=await Promise.all([id?workflowPages(id):Promise.resolve([]),id?api.runs(page.value,id):Promise.resolve({list:[],total:0})]);if(marker!==selection||id!==projectId.value)return;allWorkflows.value=w||[];allRuns.value=r.list||[];total.value=r.total||0;const target=Number(route.query.id)||runs.value[0]?.id;if(target)await select(target);else selectedId.value=0;}catch(e){if(marker===selection)error.value=errorText(e);}}
async function select(id:number){const marker=++selection;taskSelection++;taskRequest++;attemptRequest++;documentRequest++;tasksBusy.value=false;attemptsBusy.value=false;documentBusy.value=false;detail.value=null;activeTask.value=null;document.value=null;attempts.value=[];tasks.value=[];taskPage.value=0;taskTotal.value=0;try{const result=await api.runDetail(id);if(marker!==selection)return;if(!workflows.value.some(item=>item.id===result.run.workflow_id))throw new Error('运行不属于当前项目');selectedId.value=id;detail.value=result;await loadMoreTasks();if(Number(route.query.id)!==id)router.replace({path:'/workspace/runs',query:{id:String(id)}});}catch(e){if(marker!==selection)return;detail.value=null;activeTask.value=null;selectedId.value=0;ElMessage.error(errorText(e));}}
async function loadMoreTasks(){if(!detail.value||tasksBusy.value)return;const id=detail.value.run.id,pageNo=taskPage.value+1,marker=++taskRequest;tasksBusy.value=true;try{const result=await api.runTasks(id,pageNo);if(marker!==taskRequest||detail.value?.run.id!==id)return;tasks.value.push(...(result.list||[]));taskTotal.value=result.total||0;taskPage.value=pageNo;if(!activeTask.value&&tasks.value.length)selectTask(tasks.value[0]);}catch(e){if(marker===taskRequest)ElMessage.error(errorText(e));}finally{if(marker===taskRequest)tasksBusy.value=false;}}
async function selectTask(task:Task){const marker=++taskSelection;attemptRequest++;documentRequest++;attemptsBusy.value=false;documentBusy.value=false;activeTask.value=task;attempts.value=[];attemptPage.value=0;attemptTotal.value=0;document.value=null;inspectTab.value='attempts';await loadMoreAttempts(marker);}
async function loadMoreAttempts(marker=taskSelection){if(!activeTask.value||attemptsBusy.value)return;const id=activeTask.value.id,pageNo=attemptPage.value+1,request=++attemptRequest;attemptsBusy.value=true;try{const result=await api.taskAttempts(id,pageNo);if(marker!==taskSelection||request!==attemptRequest||activeTask.value?.id!==id)return;attempts.value.push(...(result.list||[]));attemptTotal.value=result.total||0;attemptPage.value=pageNo;}catch(e){if(request===attemptRequest)ElMessage.error(errorText(e));}finally{if(request===attemptRequest)attemptsBusy.value=false;}}
async function loadDocument(id:number){const taskID=activeTask.value?.id,request=++documentRequest;documentBusy.value=true;try{const result=await api.document(id);if(request===documentRequest&&taskID===activeTask.value?.id)document.value=result;}catch(e){if(request===documentRequest)ElMessage.error(errorText(e));}finally{if(request===documentRequest)documentBusy.value=false;}}
watch(projectId,async()=>{page.value=1;selectedId.value=0;await router.replace({path:'/workspace/runs'});await load();});watch(()=>route.query.id,id=>{if(Number(id)&&Number(id)!==selectedId.value)load();});onMounted(load);
</script>
<style scoped>.run-layout{display:grid;grid-template-columns:270px minmax(0,1fr) 310px;gap:16px;align-items:start}.run-list,.run-detail,.inspect{min-width:0}.section-head{display:flex;align-items:start;justify-content:space-between;gap:12px}.run-item,.task-item{width:100%;display:flex;justify-content:space-between;align-items:center;gap:10px;text-align:left;padding:12px 7px;border:0;border-top:1px solid var(--v21-line);background:#fff;color:var(--v21-ink);cursor:pointer}.run-item.active,.run-item:hover,.task-item.active,.task-item:hover{background:#eff3fb}.run-item strong,.run-item small,.task-item strong,.task-item small{display:block}.run-item small,.task-item small{font-size:11px;color:var(--v21-muted);word-break:break-word}.task-item>span:first-child{min-width:0}.pager{display:flex;align-items:center;justify-content:center;gap:8px;margin-top:15px}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin:17px 0}.metrics .v21-note{display:flex;flex-direction:column;gap:4px}.metrics strong{font-size:20px}.metrics small{color:var(--v21-muted)}.run-reason{display:flex;flex-direction:column;gap:5px;margin-bottom:18px}.run-detail h3,.inspect h3{margin:20px 0 8px}.inspect .v21-row{word-break:break-word}.inspect-tabs{display:flex;gap:8px;border-bottom:1px solid var(--v21-line);margin:16px 0}.inspect-tabs button{border:0;background:transparent;padding:10px;cursor:pointer}.inspect-tabs button.active{border-bottom:2px solid var(--v21-blue);font-weight:700}.attempt{border-bottom:1px solid var(--v21-line);padding:9px 0}.attempt small,.wrap{word-break:break-word}.json-box,.document-box{background:#f6f8fb;border:1px solid var(--v21-line);padding:11px;border-radius:8px;white-space:pre-wrap;word-break:break-word;max-height:350px;overflow:auto;font:12px/1.5 Consolas,monospace}.screenshot{width:100%;height:auto;border:1px solid var(--v21-line)}.inspect-actions{display:flex;flex-direction:column;align-items:start;gap:10px;margin-top:20px}@media(max-width:1300px){.run-layout{grid-template-columns:240px minmax(0,1fr)}.inspect{grid-column:2}.metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:760px){.run-layout{grid-template-columns:1fr}.inspect{grid-column:auto}}</style>
